{% set name = "python-dokuwiki" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fmenabe/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d0fde28e021058ad2bd2d209f131671d120dfdd3e9f735c5a8e44cb722416cf0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - dokuwiki

about:
  home: http://github.com/fmenabe/python-dokuwiki
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Manage DokuWiki via XML-RPC API
  doc_url: https://python-dokuwiki.readthedocs.io
  dev_url: http://github.com/fmenabe/python-dokuwiki

extra:
  recipe-maintainers:
    - epassaro
